### ISSUE TITLE
未能找到项目“EquationsSolver.vcxproj”

### ISSUE THREAD

**Issue by waynexu110** [tomwillow/Linkage-Mechanism-Laboratory#1]
用 Visual Studio 2015 Enterprise 打开项目时
未能正确加载解决方案中的一个或多个项目。
输出：error提示未能找到项目“EquationsSolver.vcxproj”

请问楼主怎么解决？感谢！

**Comment by tomwillow** [comment]
这个错误是因为我之前的.sln里面有2个工程，但EquationsSolver这个工程没传上来的原因。

解决方法1：手动删掉/卸载EquationsSolver工程。
解决方法2：重新clone仓库进行编译。我已经更新了新版的.sln，在vs2019下确认编译成功。

**Comment by waynexu110** [comment]
嗯，谢谢楼主，已经都解决了，感谢，你很牛！
